export const CHANGE_SEARCH_FIELD  = 'CHANGE_SEARCH_FIELD';


export const REQ_ROBOTS_PEND  = 'REQUEST_ROBOTS_PENDING';
export const REQ_ROBOTS_FAIL  = 'REQUEST_ROBOTS_FAILED';
export const REQ_ROBOTS_SUCC  = 'REQUEST_ROBOTS_SUCCESSFUL';
